README.md
> Documentation change, import of components in readme changed to point at correct npm repo.
- [-] Linked associated issue (if present)
=> Fixed typo in example component import in the "Getting Started" section

src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/FormattedValue.tsx, src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.styles.ts, src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx
- fixes #416 
- Support for values which parse to 0, previously treated as falsy rendering a value placeholder
- Support for unset twin values, now rendering as `'--'` rather than a value placeholder
- Create a numeric value widget
- Set the value to 0 (update the twin property driving the expression such that the expression results in 0) & verify the value widget shows 0
- Unset the property on the twin that is linked to the value widget & verify the widget shows '--' rather than '123' or whatever the value placeholder for that type is
=> Value widget: support for 0 & unset twin values

src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
This is a mitigation for issue [494](https://github.com/microsoft/iot-cardboard-js/issues/494)
It _does not solve the issue_ in general, it just means that we will swallow errors that occur when checking the CORS configuration, unless it is a valid 200 response and is genuinely misconfigured. 
Find yourself a storage container that you are a reader and data owner of (but not owner).  Use it against main, notice that it 403s irreparably, despite the configuration being valid.  Pull this branch down.  Notice that you can get past the 403, but if CORS is misconfigured your environment will behave erratically (you will not be able to load 3D files)
=> Swallow non 2xx response on CORS check

src/Components/ADT3DViewer/ADT3DViewer.stories.tsx, src/Components/ADT3DViewer/ADT3DViewer.tsx, src/Models/Constants/Interfaces.ts
> Extensions team need to be able to programmatically set the selected layer
> Added prop in the viewer to allow this
=> feat: Added selected layers prop to viewer

src/Components/ADT3DViewer/ADT3DViewer.tsx, src/Components/SceneBreadcrumb/BaseBreadcrumb.tsx, src/Components/SceneBreadcrumb/Internal/SceneDropdown.tsx, src/Components/SceneBreadcrumb/Internal/SceneDropdown.types.tsx, src/Components/SceneBreadcrumb/SceneBreadcrumb.types.ts, src/Components/SceneBreadcrumb/SceneBreadcrumbFactory.tsx
On view mode, when a user changes scene and has a selected element a pop-over persisted. Now the pop-over no longer persists the scene swap.
Resolves: #496 
1. Go to view mode
2. Select an item
3. Change scenes with breadcrumb
4. Pop-over should no longer appear
=> Close modal on scene change

src/Adapters/ADTAdapter.ts, src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.model.ts, src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.types.ts, src/Models/Classes/ViewerConfigUtility.ts
- Fixes [ADO bug (Twin Aliases don't work...)](https://msazure.visualstudio.com/One/_workitems/edit/14558938) by updating `getTwinIdsForBehaviorInScene` method to return Ids for all aliased twins.  Refactored modelled property builder to account for this change.  Both **PrimaryTwins** & **AliasedTwins** will now show a merged set of properties derived from the combined models of each referenced twin.  The image below shows the ModelledPropertyBuilder merging properties for `TestAlias` where `A` are the properties from a Tesla model & `B` are the properties from a Pasteurization machine model.
- Fixes [ADO bug (Aliased twins intellisense exposes the PrimaryTwin's properties)](https://msazure.visualstudio.com/One/_workitems/edit/14547801).  This seems to fix this bug as well.  Unless there …
=> Fix: Aliased Twin properties

rollup.config.js
Creates `@microsoft/iot-cardboard-js/SchemaTypes` entry point for consumers to import the generated `3DScenesConfiguration-v1.0.0.d.ts` types.
These types are exposed on their own `SchemaTypes` entry point because the types are present as auto-generated `.d.ts` files.  The build wasn't working when these were barrel exported from the root `index` file because rollup does two passes in the build process.  First, it generates the actual ESM module chunks, then it uses the [rollup-plugin-dts](https://www.npmjs.com/package/rollup-plugin-dts) plugin to rollup up the associated types for each entry point.  There's likely  a way to get the generated types to show up on the root `@microsoft/iot-cardboard-js`, but if we're ok with having them live at the `SchemaTypes` entry point -- it's an easier …
=> Export generated 3D Scenes Studio schema types

src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/StatusTab.tsx, src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.stories.tsx, src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.styles.ts, src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.tsx, src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.types.ts, src/Pages/ADT3DScenePage/ADT3DScenePage.tsx, src/Resources/Locales/cs.json, src/Resources/Locales/de.json, src/Resources/Locales/en.json, src/Resources/Locales/es.json, src/Resources/Locales/fr.json, src/Resources/Locales/hu.json, src/Resources/Locales/it.json, src/Resources/Locales/ja.json, src/Resources/Locales/ko.json, src/Resources/Locales/nl.json, src/Resources/Locales/pl.json, src/Resources/Locales/pt-pt.json, src/Resources/Locales/pt.json, src/Resources/Locales/ru.json, src/Resources/Locales/sv.json, src/Resources/Locales/tr.json, src/Resources/Locales/zh-Hans.json
Addresses [Bug 14324520](https://msazure.visualstudio.com/One/_workitems/edit/14324520): There's no way to remove "status" from a behavior once it's been configured 
Creates a clear button based on [these designs](https://www.figma.com/file/LsmZeVOZJgwZs75HPTQmgU/3D-Scenes-Mock-Screens?node-id=45547%3A225577) to be used in the Status tab.
ModelledPropertyBuilder -> Toggle Mode With Clear Button -> 
1. Select value from dropdown when Single property is toggled -> click Clear -> should say "None"
2. Toggle Custom (advanced) -> click Clear -> switch to Single property & "None"
3. Toggle …
=> "clear status" button

src/Components/3DV/SceneView.tsx
> The camera limits were clipping large models, added code to calculate maxZ and radius for the camera.
=> fix: limits to camera calculated based on model

src/Components/ADT3DViewer/ADT3DViewer.stories.tsx, src/Components/ADT3DViewer/ADT3DViewer.tsx
> If null or undefined is passed to selected layer ids prop all layers will be selected, including default layer. Required fix for the hospital demo.
=> fix: allow all layers to be selected with prop

src/Components/ADT3DViewer/ADT3DViewer.stories.tsx, src/Components/ADT3DViewer/ADT3DViewer.tsx
> When scene id was being changed on the viewer the layers were not being updated as expected. Extended story to include sceneid dropdown and updated useEffect
=> fix: Fix to selectedLayers prop when sceneid changed

src/Components/3DV/SceneView.tsx
Modified logic after model load promise is successful in SceneView to not do anything in case the user navigated away while it was still loading. Ideally the Promise can be cancelled by an `AbortController` (https://developer.mozilla.org/en-US/docs/Web/API/AbortController), however that proved to be problematic and might be overkill if this component's logic is planned to be re-written.
- Open Mock 3D Scene Page story
- Navigate to Luciana 1 scene
- While the model loads, change to another scene
- Validate the correct model is loading and previous model doesn't show up in screen at all.
Chromatic link: https://pasanch-scene-change--601c6b2fcd385c002100f14c.chromatic.com/?path=/story/pages-adt3dscenepage--mock-3-d-scene-page
=> Fix: Avoid camera issue when scene changes while loading

src/Components/ADT3DSceneBuilder/Internal/Elements/Elements.tsx
> Elements weren't always sorted correctly when changing scenes
> Updated logic to manage flag used for sorting
=> fix: elements sort fix when switching scenes

src/Components/ADT3DGlobe/ADT3DGlobe.tsx, src/Pages/ADT3DScenePage/ADT3DScenePage.tsx, src/Pages/ADT3DScenePage/ADT3DScenePage.types.ts, src/Pages/ADT3DScenePage/Internal/ADT3DSceneBuilderContainer.tsx
After some analysis of the codebase, I noticed several small details that I wanted to clean up:
1. Some props were being passed down to `ADT3DSceneBuilderContainer` are available in `DeepLinkContext` which is being used by the component. I removed that duplication in favor of the context.
2. A ref was unused in the ADT3DGlobe, which I removed.
These changes should not affect the functionality of Globe or Builder.
=> Unused prop and ref cleanup

src/Theming/Palettes.ts
Added three new Fluent icons to the Alert icon pallet.
These icons have been added so that we have more "logical" icon mappings from states,
For example:
"System Running Ok"  == "accept"
"Information" == "lightbulb"
"warning" == "warning"
These appear as in the builder as below
And Appear in the viewer as below
Run the story book and select the icons
=> Logical State Icons for Alerts

src/Components/SceneList/Internal/SceneDialog.state.ts, src/Components/SceneList/Internal/SceneDialog.tsx, src/Components/SceneList/SceneList.types.ts
When creating a new scene or editing an existing one, it was not storing the blobl URL for the selected file if you select a file from the container.
Fixes issue #653
=> Fix upload file issue for selecting existing file

src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx, src/Models/Classes/ViewerConfigUtility.ts
> When you try to delete a behavior from an element using the element form, the removal does not persist. Here is an issue that talks more about the bug: [https://github.com/microsoft/iot-cardboard-js/issues/512]. Debugging the code further, i found out that there were some lines of code that not only produced the wrong result and caused the persistence issue but weren't needed in the first place. So i removed it and things seem to be working as they should. 
> Pick or create an element that has behaviors associated with it. Try to delete and add some behaviors and see if things persist.
https://msazure.visualstudio.com/One/_workitems/edit/14759233/
=> Behavior Deletion does not persist in Elements Form

src/Components/3DV/SceneViewWrapper.styles.ts, src/Components/3DV/SceneViewWrapper.tsx, src/Components/3DV/SceneViewWrapper.types.ts, src/Components/ADT3DBuilder/ADT3DBuilder.tsx, src/Components/ADT3DBuilder/ADT3DBuilder.types.ts, src/Components/ADT3DViewer/ADT3DViewer.tsx, src/Models/Constants/Interfaces.ts
When we refactored the theme context out to a standalone control, we delayed moving the actual control to the parent. Now it's ready. So we are moving it to be with the rest of the header controls.
=> Move theme control to be with the rest of the header controls

src/Components/TooltipCallout/TooltipCallout.styles.ts, src/Components/TooltipCallout/TooltipCallout.tsx, src/Components/TooltipCallout/TooltipCallout.types.ts
See original issue here: https://github.com/microsoft/iot-cardboard-js/issues/524
The TooltipCallout component could not be interacted with. This PR addresses the bug by replacing the component's Fluent Callout with Fluent Tooltip. 
As a result, there are a few cosmetic differences (such as a change in animation), but otherwise the functionality has improved/remained the same.
Ensure that hovering/clicking behavior now works in the TooltipCallout stories.
See the fix in the original error site by going to BehaviorForm -> Edit Status Tab -> hover over Property expression "i" and ensure that you are able to click on "Learn more."
=> tooltip hover fix

src/Components/PropertyInspector/PropertyInspector.stories.local.tsx, src/Components/PropertyInspector/PropertyInspectoryModel.ts, src/Components/PropertyInspector/PropertyTree/PropertyTree.scss
Error in Property Inspector that showed up in the Explorer:
After investigation, discovered that it was caused by fields of properties that are enums not being read properly. Here is the same twin in cardboard after the fix: 
After this fix goes in, Explorer will need to be updated to consume the most recent version of cardboard.
*** IF you would prefer not to clone these models yourself, just ping me and we can walk through using my ADT instead
Repro error in Explorer: 
1. git clone this repo: https://github.com/RealEstateCore/BRECK-DTDL.git
2. do git checkout 737a1c8b63 (will revert to dtdl v2)
3. go to https://explorer.digitaltwins.azure.net/
4. Upload folder "Point" (or, if you don't want to upload all 1000 models, upload the following files: Point.json, Sensor.json, …
=> fixed error where PI could not read fields of properties that were enums

src/Components/DeeplinkFlyout/DeeplinkFlyout.tsx, src/Components/SceneRefreshButton/SceneRefreshButton.tsx
Fixes an error in the console due to unmounting the component and trying to update state in the timers.
=> Clear timeouts on unmount of scene refresh control

src/Components/SceneList/SceneList.tsx, src/Models/Hooks/useTelemetry.ts, src/Models/Services/TelemetryService/Telemetry.ts, src/Models/Services/TelemetryService/TelemetryService.ts, src/Models/Services/TelemetryService/TelemetryService.types.ts, src/Models/Services/TelemetryService/__tests__/TelemetryService.test.ts
Adds a telemetry event type for metrics and adds some logging to see telemetry even when running locally.
[Product Backlog Item 14663266](https://msazure.visualstudio.com/One/_workitems/edit/14663266): How do we do feature level app insights telemetry logging?
=> Add metrics telemetry event and rename existing types

package-lock.json, package.json, src/Adapters/ADTAdapter.ts, src/Adapters/BlobAdapter.ts, src/Adapters/BlobAdapterUtility.ts, src/Components/SceneList/SceneList.tsx, src/Models/Constants/Constants.ts, src/Models/Constants/TelemetryConstants.ts, src/Models/Context/DeeplinkContext/DeeplinkContext.tsx, src/Models/Hooks/useTelemetry.ts, src/Models/Services/TelemetryService/Telemetry.ts, src/Models/Services/TelemetryService/TelemetryService.ts, src/Models/Services/TelemetryService/TelemetryService.types.ts, src/Models/Services/TelemetryService/__tests__/TelemetryService.test.ts, src/Models/Services/Utils.test.ts, src/Models/Services/Utils.ts
Creating the initial infrastructure and events to emit KPI telemetry of the user's config file. The core of the changes are in the `BlobAdapterUtility` file. This is where we iterate through the entire config and emit events for every scene, behavior and element in the file.
The data will not actually get emitted to any telemetry service as part of Cardboard. That will be up to the hosting app to send it to a telemetry service. 
In our case, we have added that connection in the Flights app to emit the data to application insights and show it in a [PowerBI report](https://msit.powerbi.com/links/hBV4U-Y5QF?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47&pbi_source=linkShare).
You can see that all of the event names and the properties attached to each event are denoted in the `TelemetryConstants` …
=> [Telemetry] Wire up telemetry events for KPI metrics & initial user actions

src/Components/ADT3DSceneBuilder/Internal/Behaviors/Behaviors.tsx, src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/BehaviorsTab.tsx, src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.tsx, src/Models/Services/Utils.ts
> You should be able to sort the twin ids from A-Z or Z-A order.
> Click on twin id column and see if the items and arrow icon are correct
=> Enable sorting Advanced Search Results List

src/Components/EnvironmentPicker/EnvironmentPicker.tsx
Fixing a null reference when a new user comes to the site and the environment URL is not in storage already.
=> Fix null reference in environment picker

.eslintrc.json, src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx, src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx, src/Components/OATHeader/internal/FormOpen.tsx, src/Theming/FluentComponentStyles/Pivot.styles.tsx
The tabs overflow menu was throwing a react error anytime it was opened. This only showed up in other languages so it wasn't caught internally. 
The issue was that the custom rendering function on each tab item was calling a hook and since it got pushed inside the overflow set it changed the hook execution and broke the React rules for hooks always executing in the same order.
Original bug
Fixed
=> Bug Fix: Overflow tabs cause react error

src/Components/AdvancedSearch/AdvancedSearch.styles.ts, src/Components/AdvancedSearch/AdvancedSearch.tsx, src/Components/AdvancedSearch/AdvancedSearch.types.ts, src/Components/CardboardModal/CardboardModal.stories.tsx, src/Components/CardboardModal/CardboardModal.styles.ts, src/Components/CardboardModal/CardboardModal.tsx, src/Components/CardboardModal/CardboardModal.types.ts, src/Models/Constants/Types.ts
We have a lot of modals and it seemed logical that we should standardize some of that styling and components when possible so this is a generic control that conforms to most of our default styles and patterns.
This is heavily lifted from the work @pasanchMSFT did on the AdvancedSearch modal so props there! It was super easy to extract and convert to a generic implementation.
Generic modal that has title, subtitle
Generic with destructive action
Customizable title and sub title
I migrated AdvancedSearch to the generic control as an example
- Check out the `CardboardModal` stories.
=> Creating a generic modal component

src/Components/CardboardList/CardboardList.types.ts, src/Components/CardboardList/CardboardListItem.stories.tsx, src/Components/CardboardList/CardboardListItem.tsx, src/Components/ElementsPanel/Internal/ElementsList.tsx
Adding support for rendering arbitrary content at the start and end of the list item in place of the icons.
Consumers will be responsible for dealing with the right amount of spacing on the start icon since that would require a lot of backwards validation on existing stuff to add a stack.
Both start & end customized
Start only
End only
Check the following stories
=> CardboardList: Add custom icon support to cardboard list

src/Components/CardboardList/CardboardList.stories.tsx, src/Components/CardboardList/CardboardList.types.ts, src/Components/CardboardList/CardboardListItem.stories.tsx, src/Components/CardboardList/CardboardListItem.styles.ts, src/Components/CardboardList/CardboardListItem.tsx
Adding some styling to mark a list item as selected without needing the full checkbox UI.
=> CardboardList: Add styling for selected list items

src/Adapters/MockAdapter.ts
>Addressed this issue: https://github.com/microsoft/iot-cardboard-js/issues/677
>
Go to Mock3DScenePage story
1. Click on Add scene
2. Click on CHOOSE FILE dropdown
3. 3DConfig.json shown as a choice
Expected behavior
json file should not be shown in dropdown
=> 3DConfig file showing as a selectable 3D asset 

src/Components/OATGraphViewer/OATGraphViewer.types.ts, src/Models/Context/OatPageContext/OatPageContext.tsx, src/Models/Services/OatUtils.ts, src/Pages/OATEditorPage/OATEditorPage.tsx
The previous project id was not getting parsed correctly and thus wasn't loading up the right project on boot.
=> OAT: Bug fix for loading previous project into context

src/Components/CardboardList/CardboardListItem.styles.ts, src/Components/CardboardList/CardboardListItem.tsx, src/Components/ElementsPanel/ViewerElementsPanel.styles.ts, src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.styles.ts, src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.tsx, src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.types.ts, src/Components/OATGraphViewer/OATGraphViewer.styles.tsx, src/Components/OATGraphViewer/OATGraphViewer.tsx, src/Components/OATGraphViewer/OATGraphViewer.types.ts, src/Components/OATModelList/OATModelList.styles.tsx, src/Components/OATModelList/OATModelList.tsx, src/Components/OATModelList/OATModelList.types.ts, src/Models/Constants/OatStyleConstants.ts, src/Models/Hooks/useExtendedTheme.ts, src/Pages/OATEditorPage/OATEditorPage.stories.tsx, src/Pages/OATEditorPage/OATEditorPage.tsx, src/Pages/OATEditorPage/OATEditorPage.types.ts, src/Theming/FluentThemes.ts, src/Theming/Palettes.ts, src/Theming/Theme.types.ts
Styling the model list to match designs.
Before
After
=> OAT: styling the model list to use the custom color palette

src/Components/HighChartsWrapper/HighChartsWrapper.tsx
Fix for build. The error I was getting in flights app was .defaultOptions and I downloaded the HighCharts stock zipped library to see where it is called and noticed that it was in accessibility module. I noticed that I used "import" to import one module but "require" for another one. Used import for accessibility module too as suggested [here](https://github.com/highcharts/highcharts-react/issues/141)
You can test by building cardboard locally with `>npm run build` and install it in flights app (on the branch that my PR is up for) using `>npm install <full path to tgz file in build artifacts folder in cardboard>` and run there with `>npm start`.
=> [Bugfix] Highchart module import fix for build

src/Models/Hooks/useExtendedTheme.ts, src/Theming/FluentThemes.ts, src/Theming/Palettes.ts, src/Theming/Theme.types.ts
Adding a custom palette extension to the base theme. To use it, simply call `useExtendedTheme` instead of the fluent `useTheme` and pass that to your styles file as an `IExtendedTheme` instead of `ITheme` and you should be rocking and rolling. 
None.
=> Styling: Add extended palette to the theme

src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.styles.ts, src/Components/OATGraphViewer/OATGraphViewer.styles.tsx, src/Components/OATGraphViewer/OATGraphViewer.tsx, src/Components/OATGraphViewer/OATGraphViewer.types.ts, src/Components/OATModelList/OATModelList.styles.tsx, src/Components/OATPropertyEditor/Editor.tsx, src/Components/OATPropertyEditor/Editor.types.ts, src/Components/OATPropertyEditor/Internal/FormRootModelDetails.tsx, src/Components/OATPropertyEditor/Internal/FormRootModelDetails.types.ts, src/Components/OATPropertyEditor/Internal/PropertiesModelSummary.tsx, src/Components/OATPropertyEditor/Internal/PropertiesModelSummary.types.ts, src/Components/OATPropertyEditor/Internal/PropertyList.tsx, src/Components/OATPropertyEditor/Internal/PropertyList.types.ts, src/Components/OATPropertyEditor/OATPropertyEditor.stories.tsx, src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts, src/Components/OATPropertyEditor/OATPropertyEditor.tsx, src/Components/OATPropertyEditor/OATPropertyEditor.types.ts, src/Models/Constants/OatStyleConstants.ts, src/Models/Context/OatPageContext/OatPageContext.mock.ts, src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx, src/Pages/OATEditorPage/OATEditorPage.styles.tsx, src/Pages/OATEditorPage/OATEditorPage.tsx
Restyling the property editor on the right side to be floating instead of a fixed side panel.
[Product Backlog Item 15667901](https://msazure.visualstudio.com/One/_workitems/edit/15667901): OAT: Make property inspector container floating and hidable
Before
After
Also hides the panel when nothing is selected.
=> OAT: Restyle property editor

src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.tsx
Fixed the target HTML element for Conditions callout. Now it targets the Cardboard list items instead of the list itself.
Open visual rules list form, click on several Condition list items and notice how the callout changes where it is rendered.
=> Fix target for conditions callout

src/Models/Classes/3DVConfig.ts
When saving a Condition without an `iconName` a schema issue would pop-up that broke the whole app. This resolves the issue by changing the default condition to use undefined instead of null, one is schema safe (undefined) the other (null) is not.
- Add a condition to an existing visual rule, this condition should be mesh/element coloring and not have an icon.
=> Resolve Conditions on save schema issue

src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilderUtils.ts
Contains and Not Contains can now be used in advanced search. Previous issue had to do with appending combinators (AND/OR) without any spaces after them.
Go to advanced search with live data
Try searching for twins with 2 or more contains/not contains clauses.
=> Fix several Contains functions in advanced search

src/Components/ADT3DSceneBuilder/Internal/Behaviors/Twins/BehaviorTwinAliasForm.tsx, src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx, src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/ElementTwinAliasForm.tsx, src/Components/TwinSearch/TwinSearch.stories.tsx, src/Components/TwinSearch/TwinSearch.styles.ts, src/Components/TwinSearch/TwinSearch.tsx, src/Components/TwinSearch/TwinSearch.types.ts
Created `TwinSearch` component that includes `TwinPropertySearchDropdown`, `PropertyInspector`, and `AdvancedSearch`. Updated Element form and Twin alias forms to use it.
- `TwinSearch` component story
- Update a behavior by adding a new twin alias, the form should now have `TwinSearch` component.
- Editing the twin alias should also have `TwinSearch`.
- Element form should now have `TwinSearch` component and functionality should be the same.
=> Create twin search component and use where needed

src/Components/EnvironmentPicker/EnvironmentPicker.tsx, src/Components/ResourcePicker/ResourcePicker.tsx
- There was a bug in displaying error message when a resource not found - it was disappearing after on mount. 
- Also fixed casing in search to make it case insensitive
On ADT3DScenePage story:
- Change your adt hostUrl, storage account id and blobContainerUrl to a resource that does not exist in your secrets file like:
- Go to Environment Picker and see the error message persist
Also check casing in filtering by searching upper case and lower case letter.
=> [Environment Picker] Fixed error message disappearing and made filter case insensitive

src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.tsx, src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.types.ts, src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.tsx
Fixes following bugs:
- Condition range turns to null after user inputs Infinity
- Condition amount does not change Save button disabled
Also removes some unused lines.
- Create a new visual rule
- When adding a condition input -Infinity or Infinity in the number range input fields. (This should lead to the range having infinity set as one the values)
- Add a condition when the rule has none. (This should remove the disabled state of the save button)
- Remove a condition if the rule only has one. (This should add the disabled state of the save button)
=> Fix bugs in Visual rules

src/Adapters/__mockData__/MockGaugeData.json, src/Components/BehaviorsModal/Internal/Widgets/GaugeWidget/GaugeWidget.stories.tsx, src/Components/BehaviorsModal/Internal/Widgets/GaugeWidget/GaugeWidget.tsx, src/Models/Services/Utils.ts
> Today, gauges only show integers... which is tough because a lot of values are only decimals. Added formatNumber() function to allow users to view decimal and large numbers with the appropriate amount of sig figs.  
> Take a look at the Gauge Widget Stories and also, create gauge widgets with decimal or large numbers and verify that the appropriate number is displayed.
https://msazure.visualstudio.com/One/_workitems/edit/14610114/
=> Gauge widget should be configurable to show decimals

src/Theming/Palettes.ts
> Update neutralTertialAlt from a near black to a grey used when adding map key is disabled. 
Before: 
After: 
=> Ocean theme seems resolved. Dark has a regression

src/Models/Classes/ViewerConfigUtility.ts, src/Models/Classes/__tests__/ViewerConfigUtility.test.ts
Adding tests to Viewer config utility functionality. Part one, will keep adding tests as time permits.
Testing of these should be done by our build.
=> Add Viewer config utility tests, part 1

src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.styles.ts, src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.tsx, src/Resources/Styles/ReactSelect.styles.ts
- Fixed double scrollbar issue in the `TwinPropertySearchDropdown` component which consumes CreatableSelect from react-select package
- Fixed style issues like missing react-select "Menu" component in `TwinPropertySearchDropdown`
- Fixed the custom Menu and MenuList react-select components to make the onScroll callback (`handleOnScroll`) work again with scroll (to fetch the next bulk of options with adapter call)
You can test it in TwinSearch story, but also all the places where the TwinPropertySearchDropdown component is used:
- TwinSearch (It is in Element form in Elements tab in the 3DScene builder)
- QueryBuilderRow in advanced twin search which is opened from TwinSearch
=> [React-select]: Styling fixes

src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
=> Ensure that we write the configuration value for local storage on deeplink as a JSON object using appAdtUrl instead of as a string literal

src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx, src/Components/OATModelList/OATModelList.tsx
Adding larger click target along edges to make it easier to select
Adding ability to show the stacked model list when the edge is hovered instead of only on select.
Swapping from display name to unique model name in the model list
Before
After
=> OAT: Polishing graph experience

src/Models/Context/OatPageContext/OatPageContext.tsx, src/Models/Context/OatPageContext/OatPageContext.types.ts, src/Models/Context/OatPageContext/OatPageContextUtils.ts, src/Models/Services/OatUtils.ts, src/Pages/OATEditorPage/Internal/Classes/OatTypes.ts, src/Pages/OATEditorPage/Internal/Classes/ProjectData.ts
Fixing this bug where making a change, switching ontologies, make another change --> crash the app
=> OAT: Fix bug with switching causing crash

src/Adapters/__mockData__/MockAdapterData/MockModelData.json, src/Models/Services/Utils.ts
ADT allows models to have duplicate property names in object definitions in DTDL.  This is a problem, because our parser implementation forbids this.  The parser may also fail in other cases that are supported in ADT, but this is the only known case thus far.
When parsing models, if any model fails, the parser will return null.  In order to at least resolve _some_ of the valid models, we attempt to remove offending models by iteratively calling the parser by removing the models that do not parse.  In general, the parser implementation fails only one model at a time, so this may require multiple iterations.  This is a performance concern if the environment has a large number of offending models, but I think its a good balance to attempt to gracefully degrade with this recursive function …
=> Iteratively remove models when they fail the parser

src/Adapters/ADTAdapter.ts, src/Models/Hooks/useRuntimeSceneData.ts
When manually refreshing a scene, the twins would lose the data that had been previously fetched. The long poll was working fine but when manually triggered, they would lose their data and thus the status and alerts would disappear. 
This was due to a bug where the adapter did not think the twins were in the visible layers. The root cause is that the `callAdapter` function is capturing the selectedLayer list by value and thus when the refresh is triggered, it doesn't include the right values and passes in an empty [] so the adapter thinks it shouldn't fetch any twins. When it returns back the empty `sceneVisual` collection the alerts all go away. 
Now we are assuming that if there are no selected layers, it should fetch all twins instead which avoids this pitfall.
> [ Add any special …
=> Bug fix: Fixing the refresh issue

src/Components/OATHeader/OATHeader.tsx, src/Components/OATPropertyEditor/Internal/JSONEditor.tsx, src/Models/Context/OatPageContext/OatPageContext.mock.ts, src/Models/Services/OatPublicUtils.ts, src/Models/Services/OatUtils.ts, src/Models/Services/Utils.ts, src/Models/Services/__tests__/OatPublicUtils.test.ts, src/Models/Services/index.ts, src/Resources/Locales/cs.json, src/Resources/Locales/de.json, src/Resources/Locales/en.json, src/Resources/Locales/es.json, src/Resources/Locales/fr.json, src/Resources/Locales/hu.json, src/Resources/Locales/it.json, src/Resources/Locales/ja.json, src/Resources/Locales/ko.json, src/Resources/Locales/nl.json, src/Resources/Locales/pl.json, src/Resources/Locales/pt-pt.json, src/Resources/Locales/pt.json, src/Resources/Locales/ru.json, src/Resources/Locales/sv.json, src/Resources/Locales/tr.json, src/Resources/Locales/zh-Hans.json
Pulling out the import, export and parsing logic to a public utility file. It doesn't change the functionality, just moves it to a common place so we can iterate and expose to the ADT Explorer as well in the future.
- import a file
- import a folder
- Import a file that already exists in the ontology, see the errors
- Import a file that is not a JSON file
- Import a file that is a JSON file but the contents don't parse properly
- export ontology
=> OAT: Refactor import/export logic to public utils file

src/Components/OATHeader/OATHeader.styles.ts, src/Components/OATPropertyEditor/Editor.styles.ts, src/Components/OATPropertyEditor/Editor.tsx, src/Components/OATPropertyEditor/Editor.types.ts, src/Components/OATPropertyEditor/Internal/EditorJsonTab/EditorJsonTab.tsx, src/Components/OATPropertyEditor/Internal/JSONEditor.types.ts, src/Components/OATPropertyEditor/Internal/JSONEditor/JSONEditor.stories.tsx, src/Components/OATPropertyEditor/Internal/JSONEditor/JSONEditor.styles.ts, src/Components/OATPropertyEditor/Internal/JSONEditor/JSONEditor.tsx, src/Components/OATPropertyEditor/Internal/JSONEditor/JSONEditor.types.ts, src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts, src/Models/Constants/OatStyleConstants.ts, src/Pages/OATEditorPage/Internal/Classes/OatTypes.ts, src/Resources/Locales/cs.json, src/Resources/Locales/de.json, src/Resources/Locales/en.json, src/Resources/Locales/es.json, src/Resources/Locales/fr.json, src/Resources/Locales/hu.json, src/Resources/Locales/it.json, src/Resources/Locales/ja.json, src/Resources/Locales/ko.json, src/Resources/Locales/nl.json, src/Resources/Locales/pl.json, src/Resources/Locales/pt-pt.json, src/Resources/Locales/pt.json, src/Resources/Locales/ru.json, src/Resources/Locales/sv.json, src/Resources/Locales/tr.json, src/Resources/Locales/zh-Hans.json
- Add some padding around the header component so that it's not tight to the edge in the hosted experience
- Rename the JSON editor component and conform to templates
- Change tab name for JSON editor to 'DTDL'
=> fix: OAT: Small cleanup items

.eslintrc.json, .eslintrc.prod.json, rollup.config.js
Adding a rule to warn about console use on local but ignore it in the build like to do today. We will warn on `log` only and ignore `warn` and `error`.
=> ESLint: Add ESLint console rule & fix warnings in PRs

src/Adapters/MockAdapter.ts, src/Components/HighChartsWrapper/HighChartsWrapper.tsx, src/Models/SharedUtils/DataHistoryUtils.ts
Added check for adapter's mockData type to be returned from getTimeSeriesData method. Ideally we should specify what is the mockData is for.
You can test it in DataHistoryExplorer LargeData mock story since it is using mockData assigned when the new MockAdapter is initialized vs in any story which uses data history where mockData is initialized as a different type for the MockAdapter like ADT3DScenePage mock stories with mock scenes config:
=> [Data History Explorer]: fix mock data

.storybook/middleware.js, src/Adapters/ADT3DSceneAdapter.ts, src/Adapters/ADTAdapter.ts, src/Adapters/ADTDataHistoryAdapter.ts, src/Adapters/BlobAdapter.ts, src/Models/Constants/Constants.ts, src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
Blob adapter required some changes to be able to make CORS enabled requests. This PR addresses that need and also modifies the existing CORS conditionals to fix forcing CORS with a local storage flag.
Setting `useBlobProxy` enabled
1. Modify either `BlobAdapter` or `ADT3DScenesAdapter` to set `useBlobProxy` to true by default.
2. Run the project locally to be able to make requests.
3. Load containers from storage accounts that have CORS enabled.
Setting `forceProxy` flag
1. Set `useBlobProxy` to false.
2. Run this command in your console `localStorage.setItem('cardboard.feature.forceCORS', 'true')`.
3. Run the project locally to be able to make requests.
4. Load containers from storage accounts that have CORS enabled.
=> Added CORS condition to Blob adapter

src/Adapters/MockAdapter.ts, src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorForm.stories.tsx, src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorList.stories.tsx, src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorTwinAliasList.stories.tsx, src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.ElementTwinAliasList.stories.tsx, src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.Elements.stories.tsx, src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.VisualRuleList.stories.tsx, src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.WidgetsForm.stories.tsx, src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.WidgetsList.stories.tsx, src/Components/ADT3DSceneBuilder/Internal/Behaviors/Twins/BehaviorTwinAliasForm.stories.tsx, src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.stories.tsx, src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/ElementTwinAliasForm.stories.tsx, src/Components/DataHistoryExplorer/DataHistoryExplorer.stories.tsx, src/Components/PropertyInspector/PropertyInspectorCallout/PropertyInspectorCallout.stories.tsx, src/Models/Constants/Interfaces.ts, src/Models/SharedUtils/DataHistoryUtils.ts, src/Pages/ADT3DScenePage/ADT3DScenePage.stories.tsx
Strictly typed the mockData with subfields for sceneConfig, timeSeriesDataList, models and twins. So, now, consumer can set only the corresponding field when initializing a new instance of the MockAdapter and the internal class variables are going to be updated accordingly.
You can test it all the stories changed in this PR.
=> mockData arg fix for Mock Adapter

.eslintrc.json, src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyIcon/PropertyIcon.tsx, src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyIcon/PropertyIcon.types.ts, src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemArrayChild/PropertyListItemArrayChild.tsx, src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemMapChild/PropertyListItemMapChild.tsx, src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.stories.tsx, src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.tsx, src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.types.ts, src/Components/OATPropertyEditor/Internal/PropertyList/PropertyList.tsx, src/Models/Constants/Constants.ts, src/Models/Constants/Types.ts, src/Resources/Locales/cs.json, src/Resources/Locales/de.json, src/Resources/Locales/en.json, src/Resources/Locales/es.json, src/Resources/Locales/fr.json, src/Resources/Locales/hu.json, src/Resources/Locales/it.json, src/Resources/Locales/ja.json, src/Resources/Locales/ko.json, src/Resources/Locales/nl.json, src/Resources/Locales/pl.json, src/Resources/Locales/pt-pt.json, src/Resources/Locales/pt.json, src/Resources/Locales/ru.json, src/Resources/Locales/sv.json, src/Resources/Locales/tr.json, src/Resources/Locales/zh-Hans.json, tools/templates/component/component.js
Fixing 2 requests from Private Preview to clarify the Maps property experience
1. Give the Map Key field a different icon since it's always a string and to differentiate it from other property items.
2. Remove the overflow menu for the Map Key field since it can't do any of those things.
Also bumping the reference limit up from 200 to 250 as a point of feedback to support some out of the box ontologies.
Before
After
Check out this story to see the new experience `components-oat-oatpropertyeditor-propertylist--complex-model`
=> OAT: Give maps custom icon and remove menu

src/Adapters/ADTAdapter.ts, src/Components/PropertyInspector/PropertyTree/PropertyTree.tsx, src/Models/Constants/Constants.ts
- Removed local storage feature flag wall
- Fixed one bug about duplicate proxy url to get extended models
- After removing the feature flag from your local storage (`cardboard.feature.dataHistoryExplorer`), you can check it in Property Inspector in ADT3DScenePage stories (View mode) and see that the feature is still there.
=> [Data History Explorer]: Remove feature flags

src/Components/OATGraphViewer/OATGraphViewer.tsx, src/Components/OATHeader/OATHeader.tsx, src/Components/OATModelList/OATModelList.tsx, src/Components/OATPropertyEditor/Internal/EditorJsonTab/Internal/JSONEditor/JSONEditor.tsx, src/Components/OATPropertyEditor/Internal/EditorPropertiesTab/EditorPropertiesTab.tsx, src/Components/OATPropertyEditor/Internal/FormRootModelDetails/Internal/FormRootModelDetailsContent/PropertyDetailsEditorModalContent.tsx, src/Components/OATPropertyEditor/Internal/PropertiesModelSummary.tsx, src/Models/Constants/OatTelemetryConstants.ts, src/Models/Context/OatPageContext/OatPageContext.tsx, src/Models/Context/OatPageContext/OatPageContextUtils.ts, src/Models/Services/OatTelemetryUtils.ts, src/Models/Services/TelemetryService/TelemetryService.types.ts, src/Pages/OATEditorPage/Internal/Classes/OatTypes.ts, src/Pages/OATEditorPage/Internal/Hooks/useCommandHistory.tsx, src/Pages/OATEditorPage/OATEditorPage.tsx
Adding Telemetry to OAT actions. Added telemetry to be able to respond all these questions:
High level usage 
Daily active users
How many times does each user import and export in a day?
How many models, relationships, inheritances and components are in each import / export?
How many ontologies does each user have?
How many models are in each ontology?
How many models are v2 vs v3?
How many relationships, inheritances and components are in each ontology?
Feature usage
How often is DTDL manually edited and saved? 
How often is the path of a modal changed and saved? 
How often is the version of a model changed and saved? 
How often is a user searching for a model in the left panel? 
How often do users use the "auto layout" button? 
How often are properties added to a model and saved? 
Which …
=> OAT telemetry instrumentation

src/Adapters/ADTAdapter.ts
Fix a typo in the url of twin update call.
N/A
=> Fix typo in twin update call

src/Adapters/ADTAdapter.ts
Fixes duplication created by setting a baseURL in the axios instance used for data pusher requests. URL is now managed by `generateURL` function exclusively.
`this.axiosInstance` can only be found in the following methods of ADT Adapter:
- createModels (only found in `GenerateADTAssets.tsx` a data pusher component)
- createTwins (only found in `GenerateADTAssets.tsx` a data pusher component) 
- createRelationships (only found in `GenerateADTAssets.tsx` a data pusher component)
Try out data pusher stories locally with both CORS on and off.
=> Data pusher fix duplication in URL

src/Apps/Legion/Components/StepperWizard/Internal/Step.tsx, src/Apps/Legion/Components/StepperWizard/Internal/Step.types.ts, src/Apps/Legion/Components/StepperWizard/Internal/StepSeparator.tsx, src/Apps/Legion/Components/StepperWizard/Internal/StepSeparator.types.ts, src/Apps/Legion/Components/StepperWizard/Internal/Stepper.tsx, src/Apps/Legion/Components/StepperWizard/Internal/Stepper.types.ts, src/Apps/Legion/Components/StepperWizard/StepperWizard.scss, src/Apps/Legion/Components/StepperWizard/StepperWizard.stories.tsx, src/Apps/Legion/Components/StepperWizard/StepperWizard.tsx, src/Apps/Legion/Components/StepperWizard/StepperWizard.types.ts, src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.stories.tsx, src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.styles.ts, src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.tsx, src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.types.ts, src/Apps/Legion/Components/WizardShell/Internal/RelationshipBuilderStep/RelationshipBuilderStep.stories.tsx, src/Apps/Legion/Components/WizardShell/Internal/RelationshipBuilderStep/RelationshipBuilderStep.styles.ts, src/Apps/Legion/Components/WizardShell/Internal/RelationshipBuilderStep/RelationshipBuilderStep.tsx, src/Apps/Legion/Components/WizardShell/Internal/RelationshipBuilderStep/RelationshipBuilderStep.types.ts, src/Apps/Legion/Components/WizardShell/Internal/SaveStep/SaveStep.stories.tsx, src/Apps/Legion/Components/WizardShell/Internal/SaveStep/SaveStep.styles.ts, src/Apps/Legion/Components/WizardShell/Internal/SaveStep/SaveStep.tsx, src/Apps/Legion/Components/WizardShell/Internal/SaveStep/SaveStep.types.ts, src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.stories.tsx, src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.styles.ts, src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.tsx, src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.types.ts, src/Apps/Legion/Components/WizardShell/WizardShell.stories.tsx, src/Apps/Legion/Components/WizardShell/WizardShell.tsx, src/Apps/Legion/Models/Context/WizardNavigationContext/WizardNavigationContext.tsx, src/Apps/Legion/Models/Context/WizardNavigationContext/WizardNavigationContext.types.ts
Added WizardShell component to allow users to navigate to all 4 screens planned:
- Data source connector
- Twin verification
- Relationship builder
- Save
*Also added the skeleton component for each one of those screens/steps.
Modified `StepperWizard` component to allow navigation to be controlled by context, added this component to the Legion folder because more changes are planned for it.
Open Storybook and take a look at `WizardShell` stories to see how navigation with stepper component works.
=> WizardShell, navigation and skeleton components

src/Apps/Legion/Components/CarboardCreatableSelect/CarboardCreatableSelect.stories.tsx, src/Apps/Legion/Components/CarboardCreatableSelect/CarboardCreatableSelect.styles.ts, src/Apps/Legion/Components/CarboardCreatableSelect/CarboardCreatableSelect.tsx, src/Apps/Legion/Components/CarboardCreatableSelect/CarboardCreatableSelect.types.ts, src/Apps/Legion/Contexts/WizardDataContext/WizardDataContext.tsx, src/Apps/Legion/Models/Types.ts, src/Resources/Styles/ReactSelect.styles.ts
We keep having to add labels and such to the React-Select component so I thought I would create a wrapper that exposes all the same props but does some of the boilerplate for us.
With tooltip
With error message
?path=/story/apps-legion-components-carboardcreatableselect--base
=> Create wrapper on react-select with some defaults

src/Models/Constants/Constants.ts
- Fixed the link to the right public cardboard resources storage which was causing a CORS error for a customer with the old link which does not support the prod domain
Select the "Globe View" in any 3d scene page
=> [SceneViewer - Globe]: Public resources link fix

src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
Fixed series id inconsistency with fetched data due to creating a new guid in component lifecycle. It was a bug reported by a customer by not seeing the label of time series correctly in a data history widget in view mode. As a fix, I set the `seriesId` of the time series to the id of the data history time series in the 3d config file for consistent id mapping:
with fix:
You can test it by creating a data history widget with a time series with a label and see it in View mode using ADT3DScenePage story.
=> [Data History Widget]: Label fix in "View" mode

src/Models/Hooks/useTimeSeriesData.ts
Allows hyphen inclusive Kusto table names to be permitted. i.e. table-name will now be ['table-name'].
N/A
=> [Fix] Allow hypen inclusive Kusto table names

src/Models/Hooks/useTimeSeriesData.ts
Reverts microsoft/iot-cardboard-js#978 to retry CI.
=> fix: Allow hypen inclusive Kusto table names

package-lock.json, package.json, src/Adapters/ADTAdapter.ts, src/Adapters/ADXAdapter.ts, src/Adapters/BlobAdapter.ts
Summary of changes 🔍
Build with Axios upgrades with recent Node 18 Migration; to further addresses the Comp Gov with Upgrade axios from 0.21.4 to 0.28.0 to fix the vulnerability.
**Testing** 🧪
- I ran the build locally and in the pipelines to make sure those worked.
Hitting the localhost consuming local cardboard changes;      
- I ran storybook and it looks like all the styling stuff is still looking good.
**Checklist** ✔️
=> feat: Bump Axios to 0.28.0 and es5-ext to 0.10.63

package-lock.json, package.json
Upgrade fast-xml-parser from 4.4.0 to 4.4.1 to fix the vulnerability.
With Node Version: 18.*
- I ran the build locally and in the pipelines to make sure those worked with upgraded fast-xml-parser.
Hitting the localhost consuming local cardboard changes;
Build: 
Running PublicFork with https://explorer.digitaltwins.azure.net/
Build App (3D Scenes):
Running App:
=> feat: Bump fast-xml-parser from 4.4.0 to 4.4.1

package-lock.json, package.json, src/Adapters/ADTAdapter.ts, src/Adapters/ADXAdapter.ts, src/Adapters/BlobAdapter.ts
Summary of changes 🔍
Revert upgrades to axios due to runtime issues with CORS/ability to access container containing 3DScenes Config
=> Revert "feat: Bump Axios to 0.28.0 (#988)"
