src/Components/3DV/SceneView.tsx

1 line fix for supporting animation in robot arms

---

src/Adapters/BlobAdapter.ts

fix cors check by extracting checks to vars instead of giant if statement

---

src/Components/SceneList/SceneList.scss
src/Components/SceneList/SceneList.tsx
src/Pages/ADT3DScenePage/ADT3DScenePage.scss
src/Pages/ADT3DScenePage/ADT3DScenePage.styles.ts

Adding an illustration to the scene list when you have no scenes

Update styles on scene list & no data message for scenes

---

src/Adapters/__mockData__/DemoEnvsConfig.json

Element rename

---

src/Pages/ADT3DScenePage/Internal/ADT3DSceneBuilderContainer.tsx

dont return promise type

---

src/Components/ADT3DViewer/ADT3DViewer.tsx

Fixes #526 
[Bug 14628325](https://msazure.visualstudio.com/One/_workitems/edit/14628325): Shortlink does not respect layers that have been toggled off
The layer values in the deeplink were getting ignored with the most recent changes to auto select all layers. This fixes that issue by checking if we have values in the deeplink context on component mount and then respecting those values instead of overriding them.

Bug fix: Fix deeplinks not respecting layers

---

src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
src/Components/OATGraphViewer/OATGraphViewer.tsx
src/Components/OATHeader/OATHeader.tsx
src/Components/OATModelList/OATModelList.styles.tsx
src/Components/OATModelList/OATModelList.tsx
src/Components/OATPropertyEditor/FormUpdateProperty.tsx
src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
src/Models/Constants/Enums.ts
src/Models/Constants/Interfaces.ts
src/Models/Services/Utils.ts

ADTS-163 Changes

---

src/Components/AutoComplete/AutoComplete.tsx
src/Components/AutoComplete/CaretCoordinates.ts

> Fix compiler warning around commonModuleJS in AutoComplete
> Moved the caret JS function into a TS module

fix: Compiler warning

---

README.md

Adding some screenshots to the readme

Update readme with screenshots

---

src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
src/Components/OATGraphViewer/OATGraphViewer.tsx

* Workaround bug where edge layout is wrong after edit
* Fix restoring saved positions for untargeted relationships
* Ensure edges connect from center point of node

ADTS-183: manually calculate the source and target for edges

---

jest.setup.ts
src/Components/CardboardListCallout/CardboardListCallout.test.tsx
src/Components/CardboardListCallout/CardboardListCallout.tsx
src/Components/CardboardListCallout/CardboardListCallout.types.ts
src/Components/CardboardListCallout/__snapshots__/CardboardListCallout.test.tsx.snap

Added test file for `CardboardListCallout` component for exposing the search term on its primary action click
> Run `>npm test` or specifically `>npm test src\Components\CardboardListCallout\CardboardListCallout.test.tsx`

Test for cardboard list callout

---

.storybook/preview.js
src/Components/TestStories/Logging.stories.tsx
src/Models/Context/LoggingContextProvider.tsx
src/Models/Hooks/useLogger.ts
src/Models/Hooks/useLoggingService.ts
src/Models/Hooks/useTelemetry.ts
src/Models/Services/LoggingService/LoggingService.ts
src/Models/Services/LoggingService/LoggingService.types.ts
src/Models/Services/TelemetryService/Telemetry.ts
src/Models/Services/TelemetryService/TelemetryService.ts
src/Models/Services/TelemetryService/TelemetryService.types.ts
src/Models/Services/TelemetryService/__tests__/TelemetryService.test.ts
src/Models/Services/index.ts

Adds logging and telemetry services to Cardboard.  The logging service allows developers to keep useful logs in their code, easily disabled with a flag, to make future debugging easier.  The telemetry service handles reporting telemetry to library consumers via a callback registration system.
[ADO item](https://msazure.visualstudio.com/One/_sprints/taskboard/ADT%20ExACT/One/Custom/IoT/2206?workitem=14618768)
[Design document](https://microsoft-my.sharepoint.com/:w:/p/cocrowle/EXDjL2NjTgRBkPGDuiwEKkQBYxqCGZmzc7UQBc0EE5FaDQ?e=oCG8c9)
- Verify the logging test stories work as expected
- Verify the telemetry test cases pass

Logging and Telemetry Framework

---

src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
src/Components/OATGraphViewer/OATGraphViewer.tsx

ADTS-245 Fixing and Testing

---

src/Components/OATPropertyEditor/FormAddEnumItem.tsx
src/Components/OATPropertyEditor/FormRootModelDetails.tsx
src/Components/OATPropertyEditor/FormUpdateProperty.tsx
src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
src/Components/OATPropertyEditor/PropertyListItem.tsx
src/Components/OATPropertyEditor/PropertyListItemNest.tsx
src/Components/OATPropertyEditor/PropertyListItemNested.tsx

ADTS-230 ADTS-225 Implementations

---

src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx

ADTS-220 Changes For BezierPath

---

src/Components/ModelGroupLabel/ModelGroupLabel.tsx

> Updated ID for group badge to fix issue with attached context menu

Updated ID for context menu target to fix positioning issue

---

src/Components/SceneList/Internal/SceneDialog.tsx

In this PR changes were made that fix an issue which caused the creation of a new scene to fail in the case of uploading a file. Files were being added to config file as scenes, not as part of a scene. With this change, that should not occur anymore.
**Test this by running this branch locally**
- Create a new scene, upload a file to create the new scene.
- Your new scene should be shown in the scene list and in your config file.

Fix: Model file upload correctly creates new scene

---

.storybook/main.js

In this PR I modified the configuration of Storybook to ignore all Card related stories.
Take a look at the Chromatic published stories and see if any other are missing besides Card related ones.

Ignore Card stories when building Storybook

---

src/Components/AdvancedSearch/AdvancedSearch.stories.tsx
src/Components/AdvancedSearch/AdvancedSearch.styles.ts
src/Components/AdvancedSearch/AdvancedSearch.types.ts
src/Components/AdvancedSearch/AdvancedSearchModal.tsx
src/Components/AdvancedSearch/Internal/AdvancedSearchResults.tsx
src/Components/AdvancedSearch/Internal/QueryBuilder.tsx

Created the boilerplate code and a placeholder story for Advanced search feature work. Advanced search modal currently only contains a title, and some placeholder `<div>`s with some text.
N/A

Advanced search boilerplate

---

package-lock.json
src/Components/OATPropertyEditor/Editor.tsx

Reverted the package lock to before the ontology authoring PR and then regenerated it with those package.json changes due to some breaking build issues for webpack. It seems to work now.
What I did
1. Copy the contents of the `package-lock.json` file before the #650  PR was completed. ([file link](https://raw.githubusercontent.com/microsoft/iot-cardboard-js/48e2d70eda94406ca3a28c5dbd7ec4a10b2d1e9f/package-lock.json))
2. Paste those into my local while still having the `package.json` from the main branch
3. Run `npm ci` using that package lock to get exactly those old versions installed
4. Run `npm install` to grab the newly added packages that the Ontology Authoring PR added
5. Run `npm run storybook` to build and run the project
Before
After

Fix package lock issues that broke the build

---

package-lock.json
package.json

Just downgrading the minor version for react types by 1 click

make the react types match the react package

---

src/Components/OATHeader/internal/ModalDelete.tsx
src/Components/OATPropertyEditor/PropertiesModelSummary.tsx

Fixing a couple of imports that were not correct.

Fix import

---

schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
src/Adapters/BlobAdapter.ts
src/Adapters/BlobAdapterUtility.ts
src/Adapters/MockAdapter.ts
src/Models/Classes/ViewerConfigUtility.ts
src/Models/Context/BehaviorFormContext/BehaviorFormContext.tsx
src/Models/Context/BehaviorFormContext/BehaviorFormContext.types.ts
src/Models/Context/BehaviorFormContext/BehaviorFormContextUtility.ts
src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts

Added reducer actions to behavior form context to update the draft state of visual rules. Also updated schema to be able to handle `id` and `displayName` on `IExpressionRangeVisuals`, the data type that will be used to manage visual rules.
N/A

Added visual rule management in behavior form context and schema updates

---

src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/TwinsTab.tsx
src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/Internal/TimeSeriesList.tsx
src/Components/CardboardList/CardboardList.types.ts
src/Components/CardboardList/CardboardListItem.tsx

Adding an id prop explicitly for the list item 

CardboardList: Add id for list item

---

src/Adapters/BlobAdapter.ts

PR to conditionally apply migration to config data in case flighting for Visual rules is turned on.
N/A

Flight data migrations for Visual rules

---

src/Components/OATPropertyEditor/Internal/PropertyList.tsx
src/Components/OATPropertyEditor/Internal/PropertyListItem.types.ts
src/Components/OATPropertyEditor/Internal/PropertyListItemNest.tsx
src/Components/OATPropertyEditor/Internal/PropertyListItemNest.types.ts
src/Components/OATPropertyEditor/Internal/PropertyListMapItemNested.tsx
src/Models/Services/DtdlUtils.ts

OAT: Fixing typing errors in property editor

---

src/Adapters/__mockData__/3DScenesConfiguration.json

Formatting of mock data to enable clearer diffs in future PRs.
N/A

Format mock data

---

src/Adapters/__mockData__/DemoEnvsConfig.json
src/Adapters/__mockData__/TruckAndMachinesConfig.json
src/Components/BehaviorsModal/__mockData__/BehaviorsModalMockData.json

Fixed mock data for data history widget required fields for time series
> BehaviorForm and other data history widget stories

[Data history widget]: Mock data fix for now required field of propertyType

---

src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.tsx

> Addressing this issue: https://github.com/microsoft/iot-cardboard-js/issues/654
> Go to scene's element form and see if the primary twin dropdown list is sorted alphabetically

Sort Primary Twin Dropdown Options 

---

src/Components/OATGraphViewer/OATGraphViewer.tsx
src/Components/OATModelList/OATModelList.tsx
src/Models/Context/OatPageContext/OatPageContextUtils.ts
src/Models/Services/OatUtils.ts
src/Pages/OATEditorPage/OATEditorPage.tsx

We want to select the relationship when an untargeted node is clicked because you can't edit the node itself. 
Click on an Untargeted relationship --> should select the relationship
Click on an Untargeted node --> should select the relationship

OAT: Select untargeted relationship when node is clicked.

---

src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.model.ts
src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.styles.ts
src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.tsx
src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.types.ts
src/Models/Constants/Constants.ts
src/Models/Hooks/useFlattenedModelProperties.ts

DtId was excluded from advanced search properties before this PR. It is now possible to search by DtId in advanced search modal.
Open any advanced search stories and test out searching for a specific DtId.

Added dtid as an advanced search property

---

.storybook/useAuthParams.js

> resolves #471 
> Remove any valuable information from user secrets (make a backup first). This will tell you what you're missing.

Add console.warn for missing user keys

---

src/Components/Pickers/ColorSelectButton/ColorPicker.stories.tsx
src/Components/Pickers/Internal/Picker.base.styles.ts

colorPicker theming

---

src/Adapters/__mockData__/DemoEnvsConfig.json

Added new labels to demo visual rules. 
N/A

Add new labels to demo visual rules

---

package-lock.json
package.json

Set msal browser to fixed 2.14.2 version, which is what we use in the hosted apps

Peg msal browser to a stable version

---

.eslintrc.json
src/Components/OATGraphViewer/OATGraphViewer.types.ts
src/Models/Context/OatPageContext/OatPageContext.mock.ts
src/Models/Context/OatPageContext/OatPageContext.tsx
src/Models/Context/OatPageContext/OatPageContext.types.ts
src/Models/Context/OatPageContext/OatPageContextUtils.ts
src/Models/Context/OatPageContext/__tests__/OatPageContextUtils.test.ts

OAT: Fix staging branch build

---

src/Models/Context/OatPageContext/OatPageContextUtils.ts
src/Models/Services/OatUtils.ts

OAT: Fix test failures

---

.eslintrc.json
src/Components/OATGraphViewer/OATGraphViewer.tsx
src/Models/Context/OatPageContext/OatPageContext.tsx

Bug fix: when clicking the auto layout button, the nodes were not getting positioned. Now when you click it, they get arranged automatically to not collide.
Move some nodes to cause overlap. Then click the layout button and see them get repositioned.

OAT: Fix auto layout

---

src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
src/Components/OATGraphViewer/OATGraphViewer.tsx
src/Components/OATPropertyEditor/Internal/ModelPropertyHeader/ModelPropertyHeader.styles.ts
src/Models/Constants/OatStyleConstants.ts

- Swapping position of the name & id in the nodes
- Polish some styles in the node
- Ellipse long id on property editor header

OAT: Add ellipsing to long ids and names

---

src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
src/Components/DataHistoryExplorer/DataHistoryExplorer.stories.tsx
src/Components/DataHistoryExplorer/DataHistoryExplorer.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.stories.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.styles.ts
src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.types.ts
src/Components/DataHistoryExplorer/Internal/TimeSeriesTwinCallout/TimeSeriesTwinCallout.stories.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesTwinCallout/TimeSeriesTwinCallout.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.stories.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.styles.ts
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.types.ts
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.stories.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.styles.ts
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.types.ts
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.stories.tsx
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.styles.ts
src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.tsx
src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.stories.tsx
src/Components/HighChartsWrapper/HighChartsWrapper.styles.ts
src/Components/HighChartsWrapper/HighChartsWrapper.tsx
src/Components/HighChartsWrapper/HighChartsWrapper.types.ts
src/Components/QuickTimesDropdown/QuickTimesDropdown.tsx
src/Models/Constants/Constants.ts
src/Models/Constants/Interfaces.ts
src/Models/Services/Utils.ts
src/Models/Services/__tests__/DataHistoryUtils.test.ts
src/Models/SharedUtils/DataHistoryUtils.ts

- Deconstructed `TimeSeriesViewer` component (which is another main component of `DataHistoryExplorerModal` along with TimeSeriesBuilder) into internal components to cover corresponding tabs like **`TimeSeriesChart`** and **`TimeSeriesTable`** (in next PR)
- Replaced chart options settings with **`ChartCommandBar`** which is another internal component of TimeSeriesChart
- Moved some methods around for better consumption
- Fixed some interaction issues, updated the design and some content with feedback
Each new internal component has its mock stories. Mainly you can test it with `DataHistoryExplorerModal` component where everything comes together in

[Data History Explorer]: Revised the TimeSeriesViewer and added internal components

---

src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
src/Components/OATGraphViewer/OATGraphViewer.tsx
src/Components/OATPropertyEditor/Internal/PropertiesModelSummary.tsx
src/Models/Context/OatPageContext/OatPageContext.tsx
src/Models/Context/OatPageContext/OatPageContextUtils.ts
src/Models/Services/DtdlUtils.ts
src/Models/Services/__tests__/DtdlUtils.test.ts
src/Pages/OATEditorPage/OATEditorPage.styles.tsx

Fixing a round of P0 issues from our [punch list](https://microsoft-my.sharepoint.com/:w:/p/cschorm/EU448FTe1OdCuIVSKoruBLcBy_QSkZngFtNvhOmUxuujgA?e=1UBjmG&wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-TREATMENT&wdhostclicktime=1674061063887&web=1)
- Put some restrictions and guard rails on the naming of models, references & properties
- Fix bug when deleting models
- Fix tooltips when hovering the drag targets of a node
- Increase border for selected node

OAT: Resolving issue list part 1

---

src/Models/Hooks/index.ts
src/Models/Hooks/useRuntimeSceneData.ts

Export the runtime hook to allow external use

Export useRuntimeSceneData hook

---

src/Components/index.ts

Adding the new data pusher path to the exported components

Export data pusher

---

src/Components/3DV/SceneViewWrapper.tsx
src/Components/SceneList/SceneList.tsx

Overriding the viewer's outlined mesh items was broken.

Fix: outlined mesh items being overwritten

---

src/Pages/OATEditorPage/OATEditorPage.tsx

Small quick fix to do initialize telemetry for OAT.
N/A

Fix initialize telemetry

---

src/Apps/Legion/Contexts/WizardDataContext/WizardDataContext.tsx
src/Apps/Legion/Contexts/WizardDataContext/WizardDataContext.utils.ts
src/Apps/Legion/Hooks/useEntities.tsx
src/Apps/Legion/Hooks/useProperties.tsx
src/Apps/Legion/Hooks/useRelationships.tsx
src/Apps/Legion/Hooks/useTypes.tsx
src/Apps/Legion/Models/Wizard.types.ts
src/Apps/Legion/Models/index.ts
src/Apps/Legion/Services/WizardTypes.utils.ts

- Adding the `isNew` and `isDeleted` flags to all the type definitions in the wizard.
- Updated the context to soft delete by setting the flag instead of removing from the collection

Legion: Add `isNew` and `isDeleted` fields to wizard type definitions

---

package.json
tools/generate-component-template.js
tools/generate-legion-template.js
tools/templates/legion-component/component.js
tools/templates/legion-component/component.stories.js
tools/templates/legion-component/component.styles.js
tools/templates/legion-component/component.types.js
tools/templates/legion-component/index.js

Adding some templates for Legion that do not have Fluent's `styled` pattern. Now npm run generate can take a `new` flag to use new templates.
N/A

New non-styled templates

---

src/Adapters/ADT3DSceneAdapter.ts

>Added try/catch if ARG call fails to check the ADT instance property for private link.
Use a non-existing ADT instance host url (or an instance under another tenant) and check it on ADT3DScenesPage story

[Private Links]: Bugfix for null check if ARG fails

---

src/Components/OATHeader/OATHeader.tsx
src/Components/OATPropertyEditor/Internal/EditorPropertiesTab/EditorPropertiesTab.tsx
src/Models/Context/OatPageContext/OatPageContextUtils.ts
src/Models/Services/OatTelemetryUtils.ts
src/Pages/OATEditorPage/OATEditorPage.tsx

Metrics function is bonking on OAT. Added some null proofing to further debug the issue and resolve it correctly.
Load several Ontologies and verify telemetry is working correctly.

OAT telemetry fix

---

.storybook/main.js
src/Experiences/IndustrialMetaverse/Apps/Site/Components/Site.stories.tsx
src/Experiences/IndustrialMetaverse/Apps/Site/Components/Site.tsx

> Puts a Site.stories.tsx in place with the needed react router dom bits

Im h1/pamontg/structure

---

src/Components/CardboardModal/CardboardModal.tsx

fix: Bump version after package fixes

---

package-lock.json
package.json

Trying to fix this CG - https://msazure.visualstudio.com/One/_componentGovernance/Azure-IoT-DigitalTwins-Explorer/alert/9806442?typeId=10547803&pipelinesTrackingFilter=0

[CG] Bump babel-core version

---

src/Models/Hooks/useTimeSeriesData.ts

Reverts microsoft/iot-cardboard-js#977

Revert "[Fix] Allow hypen inclusive Kusto table names"

---

.github/workflows/release.yml

Adding release permissions based on semantic-release docs: https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions

Add release permissions

---

src/Models/Hooks/useTimeSeriesData.ts

Added a comment to understand thought process behind #977

fix: Add a comment to understand hyphen fix better

---

src/Models/Hooks/useTimeSeriesData.ts

Comment update to trigger CI, CI not grabbing latest updates.

fix: Comment

---

package-lock.json
package.json

Revert dependabot update to axios due to runtime issues with TextEncoder.

Revert axios

---

src/Adapters/JobsAdapter.ts
src/Components/JobsContainer/Internal/JobsDialog/JobsDialog.types.ts
src/Components/JobsContainer/JobsContainer.types.ts
src/Pages/JobsPage/JobsPage.stories.local.tsx
src/Pages/JobsPage/JobsPage.types.ts

Summary of changes 🔍
This PR focuses on Minor Refactoring;
Change in File Name to record the eligible changes to automatically trigger and publish the new version

fix: generate release version workaround

---

README.md
src/Models/Services/Utils.ts

fix: Bump version

---

src/Models/Constants/Constants.ts

Fixed publish, checking in to publish new version with ci.

fix: Publish

---

src/Components/3DV/SceneView.tsx

Modify logic to allow access to point to dev globe url.

Check window origin to serve dev globe

---

src/Models/Constants/Constants.ts

Update globe URL to point to new storage account.

Update to new globe URL
